In [1]:
import pandas as pd

# Investigating Patient One

In [2]:
# load one patient
file_path = "../data/raw/training/training_setA/p000001.psv" # create variable file_path containing location of file
patient = pd.read_csv(file_path, sep="|") # read text file and turn into dataframe

In [3]:
# display first five rows
patient.head()

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,WBC,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,1,0
1,97.0,95.0,NaN,98.0,75.33,NaN,19.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,2,0
2,89.0,99.0,NaN,122.0,86.00,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,3,0
3,90.0,95.0,NaN,NaN,NaN,NaN,30.0,NaN,24.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,4,0
4,103.0,88.5,NaN,122.0,91.33,NaN,24.5,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,5,0

In [4]:
patient.shape # shows number of rows and columns

(54, 41)

In [5]:
patient.info() # determine datatypes and number of missing values per variable

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 41 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   HR                49 non-null     float64
 1   O2Sat             44 non-null     float64
 2   Temp              10 non-null     float64
 3   SBP               42 non-null     float64
 4   MAP               42 non-null     float64
 5   DBP               0 non-null      float64
 6   Resp              50 non-null     float64
 7   EtCO2             0 non-null      float64
 8   BaseExcess        7 non-null      float64
 9   HCO3              2 non-null      float64
 10  FiO2              4 non-null      float64
 11  pH                7 non-null      float64
 12  PaCO2             6 non-null      float64
 13  SaO2              4 non-null      float64
 14  AST               1 non-null      float64
 15  BUN               2 non-null      float64
 16  Alkalinephos      1 non-null      float64
 17  Calcium           2 non-null      float64
 18  Chloride          2 non-null      float64
 19  Creatinine        2 non-null      float64
 20  Bilirubin_direct  0 non-null      float64
 21  Glucose           2 non-null      float64
 22  Lactate           0 non-null      float64
 23  Magnesium         2 non-null      float64
 24  Phosphate         2 non-null      float64
 25  Potassium         2 non-null      float64
 26  Bilirubin_total   1 non-null      float64
 27  TroponinI         0 non-null      float64
 28  Hct               2 non-null      float64
 29  Hgb               2 non-null      float64
 30  PTT               0 non-null      float64
 31  WBC               2 non-null      float64
 32  Fibrinogen        0 non-null      float64
 33  Platelets         2 non-null      float64
 34  Age               54 non-null     float64
 35  Gender            54 non-null     int64
 36  Unit1             0 non-null      float64
 37  Unit2             0 non-null      float64
 38  HospAdmTime       54 non-null     float64
 39  ICULOS            54 non-null     int64
 40  SepsisLabel       54 non-null     int64
dtypes: float64(38), int64(3)
memory usage: 17.4 KB

In [6]:
patient.isna().sum() # calculates sum of missing values for each column

HR                   5
O2Sat               10
Temp                44
SBP                 12
MAP                 12
DBP                 54
Resp                 4
EtCO2               54
BaseExcess          47
HCO3                52
FiO2                50
pH                  47
PaCO2               48
SaO2                50
AST                 53
BUN                 52
Alkalinephos        53
Calcium             52
Chloride            52
Creatinine          52
Bilirubin_direct    54
Glucose             52
Lactate             54
Magnesium           52
Phosphate           52
Potassium           52
Bilirubin_total     53
TroponinI           54
Hct                 52
Hgb                 52
PTT                 54
WBC                 52
Fibrinogen          54
Platelets           52
Age                  0
Gender               0
Unit1               54
Unit2               54
HospAdmTime          0
ICULOS               0
SepsisLabel          0
dtype: int64

In [7]:
missing_percentage = patient.isna().mean() *100 # calculates percentage of missing observations for each variable
missing_percentage

HR                    9.259259
O2Sat                18.518519
Temp                 81.481481
SBP                  22.222222
MAP                  22.222222
DBP                 100.000000
Resp                  7.407407
EtCO2               100.000000
BaseExcess           87.037037
HCO3                 96.296296
FiO2                 92.592593
pH                   87.037037
PaCO2                88.888889
SaO2                 92.592593
AST                  98.148148
BUN                  96.296296
Alkalinephos         98.148148
Calcium              96.296296
Chloride             96.296296
Creatinine           96.296296
Bilirubin_direct    100.000000
Glucose              96.296296
Lactate             100.000000
Magnesium            96.296296
Phosphate            96.296296
Potassium            96.296296
Bilirubin_total      98.148148
TroponinI           100.000000
Hct                  96.296296
Hgb                  96.296296
PTT                 100.000000
WBC                  96.296296
Fibrinogen          100.000000
Platelets            96.296296
Age                   0.000000
Gender                0.000000
Unit1               100.000000
Unit2               100.000000
HospAdmTime           0.000000
ICULOS                0.000000
SepsisLabel           0.000000
dtype: float64

In [8]:
missing_percentage.sort_values(ascending=False) # Sorts missing percentages from biggest to smallest

Bilirubin_direct    100.000000
Unit2               100.000000
Unit1               100.000000
TroponinI           100.000000
EtCO2               100.000000
Lactate             100.000000
DBP                 100.000000
PTT                 100.000000
Fibrinogen          100.000000
Bilirubin_total      98.148148
AST                  98.148148
Alkalinephos         98.148148
Hgb                  96.296296
Glucose              96.296296
WBC                  96.296296
Potassium            96.296296
Phosphate            96.296296
Magnesium            96.296296
Hct                  96.296296
Calcium              96.296296
Creatinine           96.296296
Chloride             96.296296
BUN                  96.296296
HCO3                 96.296296
Platelets            96.296296
SaO2                 92.592593
FiO2                 92.592593
PaCO2                88.888889
pH                   87.037037
BaseExcess           87.037037
Temp                 81.481481
MAP                  22.222222
SBP                  22.222222
O2Sat                18.518519
HR                    9.259259
Resp                  7.407407
Gender                0.000000
Age                   0.000000
HospAdmTime           0.000000
ICULOS                0.000000
SepsisLabel           0.000000
dtype: float64

In [9]:
patient.describe() # calculates basic descriptive statistics for each column

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,WBC,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel
count,49.000000,44.000000,10.000000,42.000000,42.000000,0.0,50.000000,0.0,7.000000,2.00000,...,2.000000,0.0,2.000000,5.400000e+01,54.0,0.0,0.0,5.400000e+01,54.000000,54.0
mean,101.571429,91.477273,36.778000,126.809524,87.261905,NaN,24.820000,NaN,20.714286,46.50000,...,10.200000,NaN,327.500000,8.314000e+01,0.0,NaN,NaN,-3.000000e-02,27.500000,0.0
std,9.594378,3.460667,0.421078,22.422482,21.270465,NaN,4.106689,NaN,2.138090,2.12132,...,6.363961,NaN,14.849242,2.868859e-14,0.0,NaN,NaN,3.502025e-18,15.732133,0.0
min,76.000000,85.000000,36.110000,78.000000,44.000000,NaN,17.000000,NaN,18.000000,45.00000,...,5.700000,NaN,317.000000,8.314000e+01,0.0,NaN,NaN,-3.000000e-02,1.000000,0.0
25%,98.000000,89.000000,36.515000,111.875000,76.330000,NaN,22.000000,NaN,19.500000,45.75000,...,7.950000,NaN,322.250000,8.314000e+01,0.0,NaN,NaN,-3.000000e-02,14.250000,0.0
50%,104.000000,91.000000,36.725000,128.000000,87.915000,NaN,25.000000,NaN,20.000000,46.50000,...,10.200000,NaN,327.500000,8.314000e+01,0.0,NaN,NaN,-3.000000e-02,27.500000,0.0
75%,108.000000,93.000000,37.110000,138.750000,96.670000,NaN,28.750000,NaN,22.000000,47.25000,...,12.450000,NaN,332.750000,8.314000e+01,0.0,NaN,NaN,-3.000000e-02,40.750000,0.0
max,117.000000,100.000000,37.440000,181.000000,141.330000,NaN,32.000000,NaN,24.000000,48.00000,...,14.700000,NaN,338.000000,8.314000e+01,0.0,NaN,NaN,-3.000000e-02,54.000000,0.0

# Investigating First 5 Patients

In [10]:
import glob

files = glob.glob("../data/raw/training/training_setA/*.psv") # find every file ending in .psv 

len(files)

20318

In [11]:
sample_files = files[:5]
sample_files

['../data/raw/training/training_setA/p000001.psv',
 '../data/raw/training/training_setA/p000002.psv',
 '../data/raw/training/training_setA/p000003.psv',
 '../data/raw/training/training_setA/p000004.psv',
 '../data/raw/training/training_setA/p000005.psv']

In [12]:
sample_patients = [pd.read_csv(file, sep="|") for file in sample_files] # reads psv file into pandas dataframe and loops through files 1-5
len(sample_patients)

5

In [13]:
[len(patient) for patient in sample_patients] # number of observations for each patient

[54, 23, 48, 29, 48]

In [14]:
[patient.shape[1] for patient in sample_patients] # checks whether same 41 columns exist for every patient

[41, 41, 41, 41, 41]

In [15]:
missing_by_patient = [patient.isna().mean().mean() * 100 for patient in sample_patients] # overall percentage of missing measurements for each patient
missing_by_patient

[np.float64(74.52574525745258),
 np.float64(68.7168610816543),
 np.float64(65.70121951219512),
 np.float64(67.11522287636669),
 np.float64(74.4918699186992)]

In [20]:
variable_stats = [patient.describe() for patient in sample_patients] # calculate basic statistical properties of variables across 5 patients
variable_stats

[               HR       O2Sat       Temp         SBP         MAP  DBP  \
 count   49.000000   44.000000  10.000000   42.000000   42.000000  0.0
 mean   101.571429   91.477273  36.778000  126.809524   87.261905  NaN
 std      9.594378    3.460667   0.421078   22.422482   21.270465  NaN
 min     76.000000   85.000000  36.110000   78.000000   44.000000  NaN
 25%     98.000000   89.000000  36.515000  111.875000   76.330000  NaN
 50%    104.000000   91.000000  36.725000  128.000000   87.915000  NaN
 75%    108.000000   93.000000  37.110000  138.750000   96.670000  NaN
 max    117.000000  100.000000  37.440000  181.000000  141.330000  NaN

             Resp  EtCO2  BaseExcess      HCO3  ...        WBC  Fibrinogen  \
 count  50.000000    0.0    7.000000   2.00000  ...   2.000000         0.0
 mean   24.820000    NaN   20.714286  46.50000  ...  10.200000         NaN
 std     4.106689    NaN    2.138090   2.12132  ...   6.363961         NaN
 min    17.000000    NaN   18.000000  45.00000  ...   5.700000         NaN
 25%    22.000000    NaN   19.500000  45.75000  ...   7.950000         NaN
 50%    25.000000    NaN   20.000000  46.50000  ...  10.200000         NaN
 75%    28.750000    NaN   22.000000  47.25000  ...  12.450000         NaN
 max    32.000000    NaN   24.000000  48.00000  ...  14.700000         NaN

         Platelets           Age  Gender  Unit1  Unit2   HospAdmTime  \
 count    2.000000  5.400000e+01    54.0    0.0    0.0  5.400000e+01
 mean   327.500000  8.314000e+01     0.0    NaN    NaN -3.000000e-02
 std     14.849242  2.868859e-14     0.0    NaN    NaN  3.502025e-18
 min    317.000000  8.314000e+01     0.0    NaN    NaN -3.000000e-02
 25%    322.250000  8.314000e+01     0.0    NaN    NaN -3.000000e-02
 50%    327.500000  8.314000e+01     0.0    NaN    NaN -3.000000e-02
 75%    332.750000  8.314000e+01     0.0    NaN    NaN -3.000000e-02
 max    338.000000  8.314000e+01     0.0    NaN    NaN -3.000000e-02

           ICULOS  SepsisLabel
 count  54.000000         54.0
 mean   27.500000          0.0
 std    15.732133          0.0
 min     1.000000          0.0
 25%    14.250000          0.0
 50%    27.500000          0.0
 75%    40.750000          0.0
 max    54.000000          0.0

 [8 rows x 41 columns],
               HR      O2Sat       Temp         SBP         MAP        DBP  \
 count  22.000000   22.00000   6.000000   15.000000   22.000000  15.000000
 mean   60.954545   97.00000  36.165000  136.600000   66.704545  44.066667
 std     8.144395    2.13809   0.151625   20.180613   14.720134   7.095941
 min    54.000000   94.00000  36.000000  114.000000   50.500000  36.000000
 25%    57.000000   95.00000  36.110000  123.500000   58.000000  41.000000
 50%    60.000000   97.00000  36.110000  133.000000   65.000000  43.000000
 75%    62.750000   99.00000  36.192500  143.000000   73.500000  45.000000
 max    94.000000  100.00000  36.440000  194.000000  116.000000  66.000000

             Resp  EtCO2  BaseExcess  HCO3  ...   WBC  Fibrinogen  Platelets  \
 count  19.000000    0.0         0.0   1.0  ...   1.0         0.0        1.0
 mean   14.236842    NaN         NaN  22.0  ...  11.0         NaN      158.0
 std     4.667763    NaN         NaN   NaN  ...   NaN         NaN        NaN
 min     9.000000    NaN         NaN  22.0  ...  11.0         NaN      158.0
 25%    11.000000    NaN         NaN  22.0  ...  11.0         NaN      158.0
 50%    12.000000    NaN         NaN  22.0  ...  11.0         NaN      158.0
 75%    16.750000    NaN         NaN  22.0  ...  11.0         NaN      158.0
 max    27.000000    NaN         NaN  22.0  ...  11.0         NaN      158.0

                 Age  Gender  Unit1  Unit2   HospAdmTime    ICULOS  SepsisLabel
 count  2.300000e+01    23.0   23.0   23.0  2.300000e+01  23.00000         23.0
 mean   7.591000e+01     0.0    0.0    1.0 -9.860000e+01  12.00000          0.0
 std    2.906048e-14     0.0    0.0    0.0  2.906048e-14   6.78233          0.0
 min    7.591000e+01     0.0    0.0    1.0 -9.860000e+01   1.00000          0.0
 25%    7.591000e+01     0.0    0.0    1.0 -9.860000e+01   6.50000          0.0
 50%    7.591000e+01     0.0    0.0    1.0 -9.860000e+01  12.00000          0.0
 75%    7.591000e+01     0.0    0.0    1.0 -9.860000e+01  17.50000          0.0
 max    7.591000e+01     0.0    0.0    1.0 -9.860000e+01  23.00000          0.0

 [8 rows x 41 columns],
               HR      O2Sat       Temp         SBP        MAP        DBP  \
 count  45.000000  44.000000  16.000000   45.000000  45.000000  42.000000
 mean   79.611111  95.431818  37.609375  140.033333  81.048000  54.392857
 std     6.714036   1.655122   0.565597    8.954684   7.854301   5.258600
 min    68.000000  91.000000  36.890000  122.000000  62.670000  44.000000
 25%    72.500000  94.000000  37.097500  135.000000  75.000000  51.000000
 50%    81.000000  95.000000  37.585000  140.000000  81.000000  53.500000
 75%    84.000000  97.000000  38.060000  146.000000  86.000000  56.750000
 max    93.000000  99.000000  38.610000  159.000000  99.000000  69.000000

             Resp  EtCO2  BaseExcess       HCO3  ...        WBC  Fibrinogen  \
 count  45.000000    0.0     2.00000   3.000000  ...   3.000000         0.0
 mean   25.633333    NaN     6.50000  30.666667  ...   9.000000         NaN
 std     4.247192    NaN     2.12132   1.527525  ...   0.888819         NaN
 min    17.000000    NaN     5.00000  29.000000  ...   8.300000         NaN
 25%    23.000000    NaN     5.75000  30.000000  ...   8.500000         NaN
 50%    26.000000    NaN     6.50000  31.000000  ...   8.700000         NaN
 75%    28.000000    NaN     7.25000  31.500000  ...   9.350000         NaN
 max    40.000000    NaN     8.00000  32.000000  ...  10.000000         NaN

         Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
 count    3.000000  48.00    48.0   48.0   48.0        48.00   48.00
 mean   479.666667  45.82     0.0    1.0    0.0     -1195.71   24.50
 std     12.741010   0.00     0.0    0.0    0.0         0.00   14.00
 min    465.000000  45.82     0.0    1.0    0.0     -1195.71    1.00
 25%    475.500000  45.82     0.0    1.0    0.0     -1195.71   12.75
 50%    486.000000  45.82     0.0    1.0    0.0     -1195.71   24.50
 75%    487.000000  45.82     0.0    1.0    0.0     -1195.71   36.25
 max    488.000000  45.82     0.0    1.0    0.0     -1195.71   48.00

        SepsisLabel
 count         48.0
 mean           0.0
 std            0.0
 min            0.0
 25%            0.0
 50%            0.0
 75%            0.0
 max            0.0

 [8 rows x 41 columns],
                HR       O2Sat       Temp         SBP        MAP        DBP  \
 count   27.000000   27.000000   6.000000   26.000000  26.000000  14.000000
 mean   102.444444   98.203704  36.455000  113.019231  67.147308  51.428571
 std      6.337212    1.449531   0.262507    9.013857  10.048494   6.129554
 min     93.000000   95.500000  36.060000   90.000000  34.000000  44.000000
 25%     95.000000   97.000000  36.390000  108.000000  63.665000  47.000000
 50%    105.000000   98.000000  36.390000  114.500000  67.835000  50.250000
 75%    107.250000   99.500000  36.637500  117.000000  72.000000  56.875000
 max    113.000000  100.000000  36.780000  132.500000  84.000000  61.500000

             Resp  EtCO2  BaseExcess  HCO3  ...  WBC  Fibrinogen   Platelets  \
 count  26.000000    0.0         2.0   2.0  ...  1.0         0.0    2.000000
 mean   18.884615    NaN         0.0  22.0  ...  7.6         NaN  182.000000
 std     3.742480    NaN         0.0   0.0  ...  NaN         NaN   53.740115
 min    14.000000    NaN         0.0  22.0  ...  7.6         NaN  144.000000
 25%    16.000000    NaN         0.0  22.0  ...  7.6         NaN  163.000000
 50%    18.000000    NaN         0.0  22.0  ...  7.6         NaN  182.000000
 75%    21.750000    NaN         0.0  22.0  ...  7.6         NaN  201.000000
 max    26.000000    NaN         0.0  22.0  ...  7.6         NaN  220.000000

                 Age  Gender  Unit1  Unit2   HospAdmTime     ICULOS  \
 count  2.900000e+01    29.0   29.0   29.0  2.900000e+01  29.000000
 mean   6.571000e+01     0.0    0.0    1.0 -8.770000e+00  15.000000
 std    1.446239e-14     0.0    0.0    0.0  1.807799e-15   8.514693
 min    6.571000e+01     0.0    0.0    1.0 -8.770000e+00   1.000000
 25%    6.571000e+01     0.0    0.0    1.0 -8.770000e+00   8.000000
 50%    6.571000e+01     0.0    0.0    1.0 -8.770000e+00  15.000000
 75%    6.571000e+01     0.0    0.0    1.0 -8.770000e+00  22.000000
 max    6.571000e+01     0.0    0.0    1.0 -8.770000e+00  29.000000

        SepsisLabel
 count         29.0
 mean           0.0
 std            0.0
 min            0.0
 25%            0.0
 50%            0.0
 75%            0.0
 max            0.0

 [8 rows x 41 columns],
               HR     O2Sat       Temp         SBP         MAP  DBP       Resp  \
 count  24.000000  21.00000   9.000000   24.000000   17.000000  0.0  21.000000
 mean   73.916667  97.50000  36.992222  132.770833   87.088235  NaN  16.500000
 std     7.586697   0.74162   0.423520    9.908252    8.631764  NaN   1.788854
 min    61.000000  96.00000  36.220000  114.000000   73.000000  NaN  14.000000
 25%    68.500000  97.00000  36.940000  124.000000   83.000000  NaN  15.000000
 50%    73.500000  97.00000  37.220000  133.500000   87.000000  NaN  16.000000
 75%    80.000000  98.00000  37.280000  141.250000   93.000000  NaN  17.500000
 max    88.000000  99.00000  37.330000  150.000000  103.000000  NaN  21.000000

        EtCO2  BaseExcess       HCO3  ...       WBC  Fibrinogen   Platelets  \
 count    0.0         0.0   3.000000  ...  3.000000         0.0    3.000000
 mean     NaN         NaN  25.666667  ...  6.933333         NaN  279.000000
 std      NaN         NaN   2.081666  ...  1.934770         NaN    7.937254
 min      NaN         NaN  24.000000  ...  4.700000         NaN  273.000000
 25%      NaN         NaN  24.500000  ...  6.350000         NaN  274.500000
 50%      NaN         NaN  25.000000  ...  8.000000         NaN  276.000000
 75%      NaN         NaN  26.500000  ...  8.050000         NaN  282.000000
 max      NaN         NaN  28.000000  ...  8.100000         NaN  288.000000

          Age  Gender  Unit1  Unit2   HospAdmTime  ICULOS  SepsisLabel
 count  48.00    48.0   48.0   48.0  4.800000e+01   48.00         48.0
 mean   28.09     1.0    1.0    0.0 -5.000000e-02   25.50          0.0
 std     0.00     0.0    0.0    0.0  7.012323e-18   14.00          0.0
 min    28.09     1.0    1.0    0.0 -5.000000e-02    2.00          0.0
 25%    28.09     1.0    1.0    0.0 -5.000000e-02   13.75          0.0
 50%    28.09     1.0    1.0    0.0 -5.000000e-02   25.50          0.0
 75%    28.09     1.0    1.0    0.0 -5.000000e-02   37.25          0.0
 max    28.09     1.0    1.0    0.0 -5.000000e-02   49.00          0.0

 [8 rows x 41 columns]]

In [23]:
# function to find percentage of missing values per variable across 5 patients
missing_by_variable = pd.concat(
    [patient.isna().mean() * 100 for patient in sample_patients],
    axis = 1
)

missing_by_variable.columns = [f"Patient {i+1}" for i in range(len(sample_patients))]

missing_by_variable["Mean Missing %"] = missing_by_variable.mean(axis=1)

missing_by_variable.sort_values("Mean Missing %", ascending=False)

,Patient 1,Patient 2,Patient 3,Patient 4,Patient 5,Mean Missing %
Bilirubin_direct,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Fibrinogen,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
TroponinI,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
EtCO2,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Lactate,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Alkalinephos,98.148148,100.000000,100.000000,100.000000,93.750000,98.379630
Bilirubin_total,98.148148,100.000000,100.000000,100.000000,93.750000,98.379630
AST,98.148148,100.000000,100.000000,100.000000,93.750000,98.379630
PTT,100.000000,100.000000,95.833333,93.103448,95.833333,96.954023
SaO2,92.592593,100.000000,100.000000,89.655172,100.000000,96.449553
FiO2,92.592593,100.000000,85.416667,100.000000,100.000000,95.601852
PaCO2,88.888889,100.000000,95.833333,93.103448,100.000000,95.565134
WBC,96.296296,95.652174,93.750000,96.551724,93.750000,95.200039
Hgb,96.296296,95.652174,93.750000,96.551724,93.750000,95.200039
Phosphate,96.296296,95.652174,93.750000,96.551724,93.750000,95.200039
Calcium,96.296296,95.652174,93.750000,96.551724,93.750000,95.200039
BaseExcess,87.037037,100.000000,95.833333,93.103448,100.000000,95.194764
BUN,96.296296,95.652174,93.750000,93.103448,93.750000,94.510384
Chloride,96.296296,95.652174,93.750000,93.103448,93.750000,94.510384
Creatinine,96.296296,95.652174,93.750000,93.103448,93.750000,94.510384
Platelets,96.296296,95.652174,93.750000,93.103448,93.750000,94.510384
Magnesium,96.296296,95.652174,93.750000,93.103448,93.750000,94.510384
HCO3,96.296296,95.652174,93.750000,93.103448,93.750000,94.510384
Hct,96.296296,95.652174,91.666667,93.103448,93.750000,94.093717
pH,87.037037,100.000000,93.750000,89.655172,100.000000,94.088442
Glucose,96.296296,95.652174,93.750000,89.655172,93.750000,93.820729
Potassium,96.296296,95.652174,91.666667,89.655172,93.750000,93.404062
Temp,81.481481,73.913043,66.666667,79.310345,81.250000,76.524307
DBP,100.000000,34.782609,12.500000,51.724138,100.000000,59.801349
SBP,22.222222,34.782609,6.250000,10.344828,50.000000,24.719932
MAP,22.222222,4.347826,6.250000,10.344828,64.583333,21.549642
Unit1,100.000000,0.000000,0.000000,0.000000,0.000000,20.000000
Unit2,100.000000,0.000000,0.000000,0.000000,0.000000,20.000000
Resp,7.407407,17.391304,6.250000,10.344828,56.250000,19.528708
O2Sat,18.518519,4.347826,8.333333,6.896552,56.250000,18.869246
HR,9.259259,4.347826,6.250000,6.896552,50.000000,15.350727
Gender,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Age,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
HospAdmTime,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ICULOS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SepsisLabel,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000